In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# import seaborn as sns
print("Environment Ready!")

Environment Ready!

In [65]:
df = pd.read_csv(r"C:\Users\muska\OneDrive\Documents\Data-Analyst-Portfolio\Ecommerce-Sales-Analysis\dataset\Sample - Superstore.csv")

In [66]:
df.head()

,CSGroup,Profit Ratio,Category,City,Country,Customer Name,Discount,Number of Records,Order Date,Order ID,...,Ship Date,Ship Mode,State,Sub-Category (group) 2,Sub-Category (group) 3,Sub-Category (group) 4,Sub-Category (group) 5,Sub-Category (group) 6,Sub-Category (group),Sub-Category
0,A&B,16%,Furniture,Henderson,United States,Claire Gute,0%,1,08-11-2017,CA-2017-152156,...,11-11-2017,Second Class,Kentucky,Losses,Losses,Losses,"Bookcases, Supplies, Tables","Bookcases, Supplies, Tables","Bookcases, Supplies, Tables",Bookcases
1,CEF,30%,Furniture,Henderson,United States,Claire Gute,0%,1,08-11-2017,CA-2017-152156,...,11-11-2017,Second Class,Kentucky,High Profits,Profits,Profits,Chairs,Chairs,Rest,Chairs
2,Rest,47%,Office Supplies,Los Angeles,United States,Darrin Van Huff,0%,1,12-06-2017,CA-2017-138688,...,16-06-2017,Second Class,California,Less Profit,Profits,Profits,Labels,Labels,Rest,Labels
3,Rest,-40%,Furniture,Fort Lauderdale,United States,Sean O'Donnell,45%,1,11-10-2016,US-2016-108966,...,18-10-2016,Standard Class,Florida,Losses,Losses,Losses,"Bookcases, Supplies, Tables","Bookcases, Supplies, Tables","Bookcases, Supplies, Tables",Tables
4,Rest,11%,Office Supplies,Fort Lauderdale,United States,Sean O'Donnell,20%,1,11-10-2016,US-2016-108966,...,18-10-2016,Standard Class,Florida,High Profits,Profits,Profits,Storage,Storage,Rest,Storage

In [67]:
df.tail()

,CSGroup,Profit Ratio,Category,City,Country,Customer Name,Discount,Number of Records,Order Date,Order ID,...,Ship Date,Ship Mode,State,Sub-Category (group) 2,Sub-Category (group) 3,Sub-Category (group) 4,Sub-Category (group) 5,Sub-Category (group) 6,Sub-Category (group),Sub-Category
9989,Rest,10%,Technology,Los Angeles,United States,Ben Ferrer,20%,1,24-12-2015,US-2015-138247,...,29-12-2015,Standard Class,California,High Profits,Profits,Profits,Phones,Phones,Rest,Phones
9990,Rest,11%,Technology,Los Angeles,United States,Ben Ferrer,20%,1,12-07-2015,CA-2015-110184,...,16-07-2015,Standard Class,California,High Profits,Profits,Profits,Phones,Phones,Rest,Phones
9991,Rest,8%,Technology,Santa Barbara,United States,Maria Etezadi,20%,1,06-06-2017,CA-2017-160717,...,11-06-2017,Standard Class,California,High Profits,Profits,Profits,Phones,Phones,Rest,Phones
9992,Rest,-80%,Technology,Yuma,United States,Gary Hansen,70%,1,16-10-2018,CA-2018-159282,...,21-10-2018,Standard Class,Arizona,Less Profit,Profits,Profits,Machines,Machines,Rest,Machines
9993,Rest,-133%,Technology,Louisville,United States,Sharelle Roach,70%,1,17-04-2018,CA-2018-134845,...,23-04-2018,Standard Class,Colorado,Less Profit,Profits,Profits,Machines,Machines,Rest,Machines

In [68]:
df.head()

,CSGroup,Profit Ratio,Category,City,Country,Customer Name,Discount,Number of Records,Order Date,Order ID,...,Ship Date,Ship Mode,State,Sub-Category (group) 2,Sub-Category (group) 3,Sub-Category (group) 4,Sub-Category (group) 5,Sub-Category (group) 6,Sub-Category (group),Sub-Category
0,A&B,16%,Furniture,Henderson,United States,Claire Gute,0%,1,08-11-2017,CA-2017-152156,...,11-11-2017,Second Class,Kentucky,Losses,Losses,Losses,"Bookcases, Supplies, Tables","Bookcases, Supplies, Tables","Bookcases, Supplies, Tables",Bookcases
1,CEF,30%,Furniture,Henderson,United States,Claire Gute,0%,1,08-11-2017,CA-2017-152156,...,11-11-2017,Second Class,Kentucky,High Profits,Profits,Profits,Chairs,Chairs,Rest,Chairs
2,Rest,47%,Office Supplies,Los Angeles,United States,Darrin Van Huff,0%,1,12-06-2017,CA-2017-138688,...,16-06-2017,Second Class,California,Less Profit,Profits,Profits,Labels,Labels,Rest,Labels
3,Rest,-40%,Furniture,Fort Lauderdale,United States,Sean O'Donnell,45%,1,11-10-2016,US-2016-108966,...,18-10-2016,Standard Class,Florida,Losses,Losses,Losses,"Bookcases, Supplies, Tables","Bookcases, Supplies, Tables","Bookcases, Supplies, Tables",Tables
4,Rest,11%,Office Supplies,Fort Lauderdale,United States,Sean O'Donnell,20%,1,11-10-2016,US-2016-108966,...,18-10-2016,Standard Class,Florida,High Profits,Profits,Profits,Storage,Storage,Rest,Storage

In [69]:
df.shape

(9994, 29)

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CSGroup                 9994 non-null   str
 1   Profit Ratio            9994 non-null   str
 2   Category                9994 non-null   str
 3   City                    9994 non-null   str
 4   Country                 9994 non-null   str
 5   Customer Name           9994 non-null   str
 6   Discount                9994 non-null   str
 7   Number of Records       9994 non-null   int64
 8   Order Date              9994 non-null   str
 9   Order ID                9994 non-null   str
 10  Postal Code             9983 non-null   float64
 11  Manufacturer            9994 non-null   str
 12  Product Name            9994 non-null   str
 13  Profit                  9994 non-null   str
 14  Quantity                9994 non-null   int64
 15  Region                  9994 non-null   str
 16  SC group                9994 non-null   str
 17  Sales                   9994 non-null   str
 18  Segment                 9994 non-null   str
 19  Ship Date               9994 non-null   str
 20  Ship Mode               9994 non-null   str
 21  State                   9994 non-null   str
 22  Sub-Category (group) 2  9994 non-null   str
 23  Sub-Category (group) 3  9994 non-null   str
 24  Sub-Category (group) 4  9994 non-null   str
 25  Sub-Category (group) 5  9994 non-null   str
 26  Sub-Category (group) 6  9994 non-null   str
 27  Sub-Category (group)    9994 non-null   str
 28  Sub-Category            9994 non-null   str
dtypes: float64(1), int64(2), str(26)
memory usage: 2.2 MB

In [71]:
df.columns

Index(['CSGroup', 'Profit Ratio', 'Category', 'City', 'Country',
       'Customer Name', 'Discount', 'Number of Records', 'Order Date',
       'Order ID', 'Postal Code', 'Manufacturer', 'Product Name', 'Profit',
       'Quantity', 'Region', 'SC group', 'Sales', 'Segment', 'Ship Date',
       'Ship Mode', 'State', 'Sub-Category (group) 2',
       'Sub-Category (group) 3', 'Sub-Category (group) 4',
       'Sub-Category (group) 5', 'Sub-Category (group) 6',
       'Sub-Category (group)', 'Sub-Category'],
      dtype='str')

In [72]:
df.isnull()

,CSGroup,Profit Ratio,Category,City,Country,Customer Name,Discount,Number of Records,Order Date,Order ID,...,Ship Date,Ship Mode,State,Sub-Category (group) 2,Sub-Category (group) 3,Sub-Category (group) 4,Sub-Category (group) 5,Sub-Category (group) 6,Sub-Category (group),Sub-Category
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9990,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9991,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9992,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9993,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [73]:
df.isnull().sum()

CSGroup                    0
Profit Ratio               0
Category                   0
City                       0
Country                    0
Customer Name              0
Discount                   0
Number of Records          0
Order Date                 0
Order ID                   0
Postal Code               11
Manufacturer               0
Product Name               0
Profit                     0
Quantity                   0
Region                     0
SC group                   0
Sales                      0
Segment                    0
Ship Date                  0
Ship Mode                  0
State                      0
Sub-Category (group) 2     0
Sub-Category (group) 3     0
Sub-Category (group) 4     0
Sub-Category (group) 5     0
Sub-Category (group) 6     0
Sub-Category (group)       0
Sub-Category               0
dtype: int64

In [74]:
df.duplicated().sum()

np.int64(1)

In [75]:
df = df.drop_duplicates()

In [76]:
df.duplicated().sum()

np.int64(0)

In [77]:
df.shape

(9993, 29)

In [78]:
df.dtypes

CSGroup                       str
Profit Ratio                  str
Category                      str
City                          str
Country                       str
Customer Name                 str
Discount                      str
Number of Records           int64
Order Date                    str
Order ID                      str
Postal Code               float64
Manufacturer                  str
Product Name                  str
Profit                        str
Quantity                    int64
Region                        str
SC group                      str
Sales                         str
Segment                       str
Ship Date                     str
Ship Mode                     str
State                         str
Sub-Category (group) 2        str
Sub-Category (group) 3        str
Sub-Category (group) 4        str
Sub-Category (group) 5        str
Sub-Category (group) 6        str
Sub-Category (group)          str
Sub-Category                  str
dtype: object

In [79]:
df["Sales"].head()

0    $262
1    $732
2     $15
3    $958
4     $22
Name: Sales, dtype: str

In [80]:
df["Profit"].head()

0      $42
1     $220
2       $7
3    -$383
4       $3
Name: Profit, dtype: str

In [81]:
df["Profit Ratio"].head()

0     16%
1     30%
2     47%
3    -40%
4     11%
Name: Profit Ratio, dtype: str

In [82]:
df["Discount"].head()

0     0%
1     0%
2     0%
3    45%
4    20%
Name: Discount, dtype: str

In [83]:
df["Sales"].sample(10)

3415     $76
4480     $49
6717      $5
4000     $64
2007     $10
4547     $39
1637    $450
4853     $53
3149      $4
7280      $5
Name: Sales, dtype: str

In [84]:
df["Sales"] = (
    df["Sales"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

df["Sales"] = df["Sales"].astype(float)

In [85]:
df["Profit"] = (
    df["Profit"]
    .str.replace("-$", "-", regex=False)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

df["Profit"] = df["Profit"].astype(float)

In [86]:
df[["Sales", "Profit"]].dtypes

Sales     float64
Profit    float64
dtype: object

In [87]:
df["Discount"] = (
    df["Discount"]
    .str.replace("%", "", regex=False)
    .astype(float)
)

In [88]:
df["Profit Ratio"] = (
    df["Profit Ratio"]
    .str.replace("%", "", regex=False)
    .astype(float)
)

In [89]:
df["Discount"].dtype
df["Profit Ratio"].dtype

dtype('float64')

In [90]:
df["Order Date"].head()

0    08-11-2017
1    08-11-2017
2    12-06-2017
3    11-10-2016
4    11-10-2016
Name: Order Date, dtype: str

In [62]:
df["Ship Date"].head()

0    11-11-2017
1    11-11-2017
2    16-06-2017
3    18-10-2016
4    18-10-2016
Name: Ship Date, dtype: str

In [91]:
df["Order Date"].head()

0    08-11-2017
1    08-11-2017
2    12-06-2017
3    11-10-2016
4    11-10-2016
Name: Order Date, dtype: str

In [92]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%d-%m-%Y"
)

In [93]:
df.info()

<class 'pandas.DataFrame'>
Index: 9993 entries, 0 to 9993
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CSGroup                 9993 non-null   str
 1   Profit Ratio            9993 non-null   float64
 2   Category                9993 non-null   str
 3   City                    9993 non-null   str
 4   Country                 9993 non-null   str
 5   Customer Name           9993 non-null   str
 6   Discount                9993 non-null   float64
 7   Number of Records       9993 non-null   int64
 8   Order Date              9993 non-null   datetime64[us]
 9   Order ID                9993 non-null   str
 10  Postal Code             9982 non-null   float64
 11  Manufacturer            9993 non-null   str
 12  Product Name            9993 non-null   str
 13  Profit                  9993 non-null   float64
 14  Quantity                9993 non-null   int64
 15  Region                  9993 non-null   str
 16  SC group                9993 non-null   str
 17  Sales                   9993 non-null   float64
 18  Segment                 9993 non-null   str
 19  Ship Date               9993 non-null   datetime64[us]
 20  Ship Mode               9993 non-null   str
 21  State                   9993 non-null   str
 22  Sub-Category (group) 2  9993 non-null   str
 23  Sub-Category (group) 3  9993 non-null   str
 24  Sub-Category (group) 4  9993 non-null   str
 25  Sub-Category (group) 5  9993 non-null   str
 26  Sub-Category (group) 6  9993 non-null   str
 27  Sub-Category (group)    9993 non-null   str
 28  Sub-Category            9993 non-null   str
dtypes: datetime64[us](2), float64(5), int64(2), str(20)
memory usage: 2.3 MB

In [94]:
df.describe()

,Profit Ratio,Discount,Number of Records,Order Date,Postal Code,Profit,Quantity,Sales,Ship Date
count,9993.000000,9993.000000,9993.0,9993,9982.000000,9993.000000,9993.000000,9993.000000,9993
mean,12.054838,15.618833,1.0,2017-04-30 07:03:30.747523,55246.437087,28.655959,3.789753,229.868208,2017-05-04 06:03:42.635845
min,-275.000000,0.000000,1.0,2015-01-03 00:00:00,1040.000000,-6600.000000,1.000000,0.000000,2015-01-07 00:00:00
25%,7.000000,0.000000,1.0,2016-05-23 00:00:00,23223.000000,2.000000,2.000000,17.000000,2016-05-27 00:00:00
50%,27.000000,20.000000,1.0,2017-06-26 00:00:00,57103.000000,9.000000,3.000000,54.000000,2017-06-29 00:00:00
75%,36.000000,20.000000,1.0,2018-05-14 00:00:00,90008.000000,29.000000,5.000000,210.000000,2018-05-18 00:00:00
max,50.000000,80.000000,1.0,2018-12-30 00:00:00,99301.000000,8400.000000,14.000000,22638.000000,2019-01-05 00:00:00
std,46.694354,20.645729,0.0,NaN,32040.095123,234.267081,2.225149,623.279922,NaN

In [96]:
df.to_csv(r"C:\Users\muska\OneDrive\Documents\Data-Analyst-Portfolio\Ecommerce-Sales-Analysis\cleaned_data\cleaned_superset.csv",index=False)